baseURL = "https://writingasongaweek.com/"
languageCode = "en-us"
title = "Adrienne Franke"
theme = "rocinante"
paginate = 6
publishDir = "docs"

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "/icons/favicon.png"
  mainSections = ["posts", "photos"]
  email = "adriennefranke@gmail.com"
  about = """
I’m writing one song a week in 2021 and I’m posting all about it here 💿 0/52
"""

  [[params.links]]
    [[params.links.link]]
     name = 'Subscribe for email updates'
     href = "https://tinyletter.com/writingasongaweek"
     new_tab = true 

  [[params.links]]
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/adriennefranke"
      new_tab = true
    [[params.links.link]]
      name = "Instagram"
      href = "https://instagram.com/adriennefrankemusic"
      new_tab = true
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/adriennefranke"
      new_tab = true